// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXaIvNt-O04PGwnLI6sE7JOul9YHTAXw',
    appId: '1:323737700336:web:d79484c9b65c131f1f7f35',
    messagingSenderId: '323737700336',
    projectId: 'appwrite-hackathon',
    authDomain: 'appwrite-hackathon.firebaseapp.com',
    databaseURL:
        'https://appwrite-hackathon-default-rtdb.us-central1.firebasedatabase.app',
    storageBucket: 'appwrite-hackathon.appspot.com',
    measurementId: 'G-FB1BK4HF87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdnDFzjw6rqOGpMrCFmFb8pzqT-RqQOc',
    appId: '1:323737700336:android:7523e4730a74cc531f7f35',
    messagingSenderId: '323737700336',
    projectId: 'appwrite-hackathon',
    databaseURL:
        'https://appwrite-hackathon-default-rtdb.us-central1.firebasedatabase.app',
    storageBucket: 'appwrite-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRdvCchnN6944DQBfFdY3pzstVPBEtSU',
    appId: '1:323737700336:ios:89e6cc7508d2366b1f7f35',
    messagingSenderId: '323737700336',
    projectId: 'appwrite-hackathon',
    databaseURL:
        'https://appwrite-hackathon-default-rtdb.us-central1.firebasedatabase.app',
    storageBucket: 'appwrite-hackathon.appspot.com',
    iosBundleId: 'com.appwrite.hackathon.appwriteHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRdvCchnN6944DQBfFdY3pzstVPBEtSU',
    appId: '1:323737700336:ios:89e6cc7508d2366b1f7f35',
    messagingSenderId: '323737700336',
    projectId: 'appwrite-hackathon',
    databaseURL:
        'https://appwrite-hackathon-default-rtdb.us-central1.firebasedatabase.app',
    storageBucket: 'appwrite-hackathon.appspot.com',
    iosBundleId: 'com.appwrite.hackathon.appwriteHackathon',
  );
}
